<?php

declare(strict_types=1);

return [
    'errors.auth_lock_backend_failed' => 'Auth lock backend failed',
    'errors.bad_gateway' => 'Bad gateway',
    'errors.bad_request' => 'Bad request',
    'errors.client_error' => 'Client error',
    'errors.configuration_error' => 'Configuration error',
    'errors.connection_failed' => 'Connection failed',
    'errors.dns_error' => 'DNS error',
    'errors.execution_budget_exhausted' => 'Execution budget exhausted: {stage}',
    'errors.execution_error' => 'Execution error',
    'errors.extension_error' => 'Extension error',
    'errors.failed_to_record_the_completed_http_request_fixture' => 'Failed to record the completed HTTP request fixture',
    'errors.failed_to_recover_authentication_after_401' => 'Failed to recover authentication after 401',
    'errors.failed_to_refresh_authentication' => 'Failed to refresh authentication',
    'errors.file_transfer_error' => 'File transfer error',
    'errors.file_transfer_failed' => 'File transfer failed: {stage}',
    'errors.forbidden' => 'Forbidden',
    'errors.gateway_timeout' => 'Gateway timeout',
    'errors.hook_error' => 'Hook error',
    'errors.hydration_error' => 'Hydration error',
    'errors.invalid_http_request' => 'Invalid HTTP request',
    'errors.not_found' => 'Not found',
    'errors.rate_limit_exceeded' => 'Rate limit exceeded',
    'errors.rate_limit_store_failed' => 'Rate limit store failed',
    'errors.request_contract_violation' => 'Request contract violation',
    'errors.request_retry_required' => 'Request retry required',
    'errors.response_decoding_error' => 'Response decoding error',
    'errors.retry_safety_check_failed' => 'Retry safety check failed',
    'errors.return_without_http' => 'Return without HTTP',
    'errors.serialization_error' => 'Serialization error',
    'errors.server_error' => 'Server error',
    'errors.service_unavailable' => 'Service unavailable',
    'errors.timed_out_waiting_for_token_refresh' => 'Timed out waiting for token refresh',
    'errors.timeout' => 'Timeout',
    'errors.transport_error' => 'Transport error',
    'errors.unauthorized' => 'Unauthorized',
    'errors.validation_failed' => 'Validation failed',
    'hydration.invalid_value' => 'Invalid data at {value0}: expected {expected}, got {actual}',
    'hydration.invalid_value_path' => 'Invalid data at {path}: expected {value1}, got {value2}',
];
