<?php

declare(strict_types=1);

return [
    'transport.async_dns_required' => 'Concurrent Guzzle requests require cURL with AsynchDNS. Enable an asynchronous DNS resolver in cURL or use send().',
    'transport.concurrent_execution_unsupported' => 'Adapter {adapter} does not support concurrent execution. Use send() or a concurrent transport such as HttpTransport::createDefault().',
    'transport.body_cannot_be_represented_in_the_utf_8_fixture' => 'Body cannot be represented in the UTF-8 fixture format',
    'transport.curl_does_not_support_preserving_the_request_target' => 'cURL does not support preserving the request target',
    'transport.default_http_adapter_requires_guzzlehttp_guzzle_and_ext_curl' => 'Default HTTP adapter requires guzzlehttp/guzzle and ext-curl',
    'transport.does_not_support_per_request_timeout_connecttimeout_deadline_httpclientoptionsinterface' => '{value0} does not support per-request timeout/connectTimeout/deadline; HttpClientOptionsInterface is required',
    'transport.does_not_support_timeout_connecttimeout_deadline' => '{value0} does not support timeout/connectTimeout/deadline',
    'transport.failed_to_create_a_temporary_fixture_in_the_target' => 'Failed to create a temporary fixture in the target directory',
    'transport.failed_to_create_the_fixtures_directory' => 'Failed to create the fixtures directory',
    'transport.failed_to_publish_the_fixture' => 'Failed to publish the fixture',
    'transport.failed_to_remove_the_temporary_fixture' => 'Failed to remove the temporary fixture',
    'transport.fixture_does_not_contain_a_file_body_use_mockresponse' => 'Fixture does not contain a file body; use MockResponse::file()',
    'transport.fixture_is_corrupted' => 'Fixture {file} is corrupted',
    'transport.fixture_not_found' => 'Fixture {file} not found',
    'transport.fixture_not_found_for_request' => 'Fixture not found for request {requestClass}',
    'transport.fixture_path_is_not_specified' => 'Fixture path is not specified',
    'transport.fixture_was_not_written_completely' => 'Fixture was not written completely',
    'transport.for_a_custom_guzzle_handler_use_an_httpclientoptionsinterface_adapter' => 'For a custom Guzzle handler use an HttpClientOptionsInterface adapter with explicit timeout support',
    'transport.http_client_did_not_return_a_managed_download_stream' => 'HTTP client did not return a managed download stream',
    'transport.http_client_received_a_changed_request_destination' => 'HTTP client received a changed request destination',
    'transport.low_level_curl_overrides_are_incompatible_with_destination_isolation' => 'Low-level cURL overrides are incompatible with destination isolation',
    'transport.low_level_curl_overrides_are_incompatible_with_streaming_files' => 'Low-level cURL overrides are incompatible with streaming files',
    'transport.psr_17_request_factory_binding_has_an_invalid_type' => 'PSR-17 request factory binding has an invalid type',
    'transport.psr_17_stream_factory_binding_has_an_invalid_type' => 'PSR-17 stream factory binding has an invalid type',
    'transport.psr_18_client_binding_must_implement_clientinterface' => 'PSR-18 client binding must implement ClientInterface',
    'transport.psr_factory_modifies_the_absolute_request_target' => 'PSR factory modifies the absolute request target',
    'transport.request_was_not_sent' => 'Request {requestClass} was not sent',
    'transport.request_was_sent' => 'Request {requestClass} was sent',
    'transport.request_was_sent_time_s' => 'Request {requestClass} was sent {count} time(s)',
    'transport.requests_were_sent' => 'Requests were sent',
    'transport.streaming_download_requires_a_sink' => 'Streaming download requires a sink',
    'transport.transport_is_not_configured_bind_transportinterface_in_the_container' => 'Transport is not configured. Bind TransportInterface in the container or install a PSR-18 client (for example, guzzlehttp/guzzle).',
    'transport.unmocked_request' => 'Unmocked request',
];
