<?php

declare(strict_types=1);

return [
    'errors.auth_lock_backend_failed' => 'Ошибка backend auth-блокировки',
    'errors.bad_gateway' => 'Плохой шлюз',
    'errors.bad_request' => 'Некорректный запрос',
    'errors.client_error' => 'Ошибка клиента',
    'errors.configuration_error' => 'Ошибка конфигурации',
    'errors.connection_failed' => 'Ошибка подключения',
    'errors.dns_error' => 'Ошибка DNS',
    'errors.execution_budget_exhausted' => 'Исчерпан общий бюджет выполнения: {stage}',
    'errors.execution_error' => 'Ошибка исполнения',
    'errors.extension_error' => 'Ошибка расширения',
    'errors.failed_to_record_the_completed_http_request_fixture' => 'Не удалось записать fixture выполненного HTTP-запроса',
    'errors.failed_to_recover_authentication_after_401' => 'Не удалось восстановить авторизацию после 401',
    'errors.failed_to_refresh_authentication' => 'Не удалось обновить авторизацию',
    'errors.file_transfer_error' => 'Ошибка файловой передачи',
    'errors.file_transfer_failed' => 'Ошибка файловой передачи: {stage}',
    'errors.forbidden' => 'Доступ запрещен',
    'errors.gateway_timeout' => 'Таймаут шлюза',
    'errors.hook_error' => 'Ошибка hook',
    'errors.hydration_error' => 'Ошибка гидратации',
    'errors.invalid_http_request' => 'Некорректный HTTP-запрос',
    'errors.not_found' => 'Не найдено',
    'errors.rate_limit_exceeded' => 'Превышен лимит запросов',
    'errors.rate_limit_store_failed' => 'Ошибка хранилища rate-limit',
    'errors.request_contract_violation' => 'Нарушение контракта запроса',
    'errors.request_retry_required' => 'Требуется повтор запроса',
    'errors.response_decoding_error' => 'Ошибка разбора ответа',
    'errors.retry_safety_check_failed' => 'Ошибка проверки безопасности повтора',
    'errors.return_without_http' => 'Возврат без HTTP',
    'errors.serialization_error' => 'Ошибка сериализации',
    'errors.server_error' => 'Ошибка сервера',
    'errors.service_unavailable' => 'Сервис недоступен',
    'errors.timed_out_waiting_for_token_refresh' => 'Истекло время ожидания обновления токена',
    'errors.timeout' => 'Таймаут',
    'errors.transport_error' => 'Ошибка транспорта',
    'errors.unauthorized' => 'Не авторизован',
    'errors.validation_failed' => 'Ошибка валидации',
    'hydration.invalid_value' => 'Некорректные данные в {value0}: ожидается {expected}, получено {actual}',
    'hydration.invalid_value_path' => 'Некорректные данные в {path}: ожидается {value1}, получено {value2}',
];
