<?php

declare(strict_types=1);

return [
    'transport.async_dns_required' => 'Конкурентным запросам Guzzle требуется cURL с AsynchDNS. Подключите асинхронный DNS в cURL или используйте send().',
    'transport.concurrent_execution_unsupported' => 'Адаптер {adapter} не поддерживает конкурентное выполнение. Используйте send() или конкурентный транспорт, например HttpTransport::createDefault().',
    'transport.body_cannot_be_represented_in_the_utf_8_fixture' => 'Тело не представимо в UTF-8 формате fixture',
    'transport.curl_does_not_support_preserving_the_request_target' => 'cURL не поддерживает сохранение request target',
    'transport.default_http_adapter_requires_guzzlehttp_guzzle_and_ext_curl' => 'Штатный HTTP-адаптер требует guzzlehttp/guzzle и ext-curl',
    'transport.does_not_support_per_request_timeout_connecttimeout_deadline_httpclientoptionsinterface' => '{value0} не поддерживает per-request timeout/connectTimeout/deadline; нужен HttpClientOptionsInterface',
    'transport.does_not_support_timeout_connecttimeout_deadline' => '{value0} не поддерживает timeout/connectTimeout/deadline',
    'transport.failed_to_create_a_temporary_fixture_in_the_target' => 'Не удалось создать временную fixture в целевом каталоге',
    'transport.failed_to_create_the_fixtures_directory' => 'Не удалось создать каталог fixtures',
    'transport.failed_to_publish_the_fixture' => 'Не удалось опубликовать fixture',
    'transport.failed_to_remove_the_temporary_fixture' => 'Не удалось удалить временную fixture',
    'transport.fixture_does_not_contain_a_file_body_use_mockresponse' => 'Фикстура не содержит файловое тело; используйте MockResponse::file()',
    'transport.fixture_is_corrupted' => 'Фикстура {file} повреждена',
    'transport.fixture_not_found' => 'Фикстура {file} не найдена',
    'transport.fixture_not_found_for_request' => 'Фикстура для запроса {requestClass} не найдена',
    'transport.fixture_path_is_not_specified' => 'Не указан путь к фикстурам',
    'transport.fixture_was_not_written_completely' => 'Fixture записана не полностью',
    'transport.for_a_custom_guzzle_handler_use_an_httpclientoptionsinterface_adapter' => 'Для собственного Guzzle handler используйте адаптер HttpClientOptionsInterface с явной поддержкой таймаутов',
    'transport.http_client_did_not_return_a_managed_download_stream' => 'HTTP-клиент не вернул управляемый поток download',
    'transport.http_client_received_a_changed_request_destination' => 'HTTP-клиент получил изменённое назначение запроса',
    'transport.low_level_curl_overrides_are_incompatible_with_destination_isolation' => 'Низкоуровневые cURL overrides несовместимы с изоляцией назначения',
    'transport.low_level_curl_overrides_are_incompatible_with_streaming_files' => 'Низкоуровневые cURL overrides несовместимы с потоковыми файлами',
    'transport.psr_17_request_factory_binding_has_an_invalid_type' => 'Binding PSR-17 request factory имеет неверный тип',
    'transport.psr_17_stream_factory_binding_has_an_invalid_type' => 'Binding PSR-17 stream factory имеет неверный тип',
    'transport.psr_18_client_binding_must_implement_clientinterface' => 'Binding PSR-18 клиента должен реализовывать ClientInterface',
    'transport.psr_factory_modifies_the_absolute_request_target' => 'PSR-фабрика изменяет готовый request target',
    'transport.request_was_not_sent' => 'Запрос {requestClass} не был отправлен',
    'transport.request_was_sent' => 'Запрос {requestClass} был отправлен',
    'transport.request_was_sent_time_s' => 'Запрос {requestClass} был отправлен {count} раз(а)',
    'transport.requests_were_sent' => 'Были отправлены запросы',
    'transport.streaming_download_requires_a_sink' => 'Потоковый download требует sink',
    'transport.transport_is_not_configured_bind_transportinterface_in_the_container' => 'Транспорт не настроен. Передайте TransportInterface через контейнер или установите PSR-18 клиент (например, guzzlehttp/guzzle).',
    'transport.unmocked_request' => 'Незамоканный запрос',
];
